### ISSUE TITLE
[BUG] Terrad export cannot create new genesis

### ISSUE THREAD

**Issue by edk208** [terra-rebels/classic-core#10]
**Describe the bug**
exporting the state from mainnet cannot create a new genesis.  

**To Reproduce**
~/go/bin/terrad migrate --chain-id=rebel-1 --initial-height=10000000 col5_8766463.json > genesis.json
panic: JSON encoding of interfaces require non-empty type field.

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*LegacyAmino).MustUnmarshalJSON(...)
	github.com/cosmos/cosmos-sdk@v0.44.5/codec/amino.go:171
github.com/terra-money/core/app/legacy/v05.Migrate(0x14000604030, {{0x0, 0x0, 0x0}, {0x104b52878, 0x140012947b0}, {0x16d17faa6, 0x7}, {0x104b237c0, 0x14000122980}, ...})
	github.com/terra-money/core/app/legacy/v05/migrate.go:76 +0x21f4
github.com/terra-money/core/app/legacy.MigrateGenesisCmd.func1(0x14000ea5b80, {0x14001294000, 0x1, 0x3})
	github.com/terra-money/core/app/legacy/migrate.go:80 +0x170
github.com/spf13/cobra.(*Command).execute(0x14000ea5b80, {0x14001245f80, 0x3, 0x3})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x14000ea5400)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14000ea5400, {0x14000199740, 0x13})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x23c
main.main()
	github.com/terra-money/core/cmd/terrad/main.go:15 +0x3c

**Context & versions**
Exporting from mainnet.  I cannot create a new genesis from it.

**(if applicable) suggested solution**
working on it.  terrad migrate doesn't seem to work

**Comment by edk208** [comment]
No need to migrate, instead just use as new genesis but getting this error now instead

~/go/bin/terrad start
10:00AM INF starting ABCI with Tendermint
panic: snappy: decoded block is too large

goroutine 1 [running]:
github.com/golang/snappy.Encode({0x14000054100, 0x4, 0x4}, {0x14a4cdb4000, 0x24a633669, 0x24a6336c8})
	github.com/golang/snappy@v0.0.3/encode.go:22 +0x280

**Comment by ZaradarDFDS** [comment]
Seems like the byte[] your passing to snappy exceed the max len check here: https://github.com/golang/snappy/blob/fa5810519dcbfaa60974183cbe11c6c0d050a23d/encode.go#L21

If you read the comments here: https://github.com/golang/snappy/blob/fa5810519dcbfaa60974183cbe11c6c0d050a23d/encode.go#L83 it seems to indicate that a your input is violating the length check thus causing it to return -1 which panics the encoder. Is it possible for you to add a log statement so we can see the contents of the byte array and figure out why its violating the snappy block size?

**Comment by edk208** [comment]
new genesis can pass if all the wasm code is wiped out.  It also takes the genesis down from 9GB to 3GB.  Use of jq can remove the wasm json.
jq 'del(.app_state.wasm)' col5_8766463.json >col5_nowasm.json

when starting terrad, asserting crisis invariants takes 2 days to finish.
asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
better start terrad with terrad start --x-crisis-skip-assert-invariants
